version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"      # (opcjonalnie) agent communication
      - "9443:9443"      # HTTPS interfejs webowy
      - "9000:9000"      # (opcjonalnie) HTTP interfejs webowy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
